
name: docker ci

on:
  push:
    branches:
      - main
jobs:

  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t file-management

    - name: Push the Docker image
      run: docker push file-management:latest
    
