
name: docker ci

on:
  push:
    branches:
      - main
jobs:

  build:
   
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub

      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build ./server/file-management -t file-management:latest

    - name: Tag the Docker image
      run: docker tag file-management:latest ${DOCKER_USERNAME}/file-management:latest

    - name: Push the Docker image
      run: docker push ${DOCKER_USERNAME}/file-management:latest
    
